import httpx
import os

WHATSAPP_TOKEN    = ""
WHATSAPP_PHONE_ID = ""
WHATSAPP_TO       = ""

def run_alert_agent(machine_id, root_cause, confidence, impact, suggested_fix):
    if impact["severity"] == "HIGH" and confidence > 0.8:
        priority = "P1"
    elif impact["severity"] == "MEDIUM" or confidence > 0.6:
        priority = "P2"
    else:
        priority = "P3"
    message = (
        f"MACHINE ALERT - ADIAP\n\n"
        f"Machine: {machine_id}\n"
        f"Issue: {root_cause}\n"
        f"Confidence: {int(confidence * 100)}%\n"
        f"Potential Loss: Rs{impact['total_impact']:,}\n\n"
        f"Action: {suggested_fix}\n\n"
        f"Generated by ADIAP - AI Downtime Intelligence Platform"
    )
    return {"priority": priority, "message": message, "machine_id": machine_id}

async def send_whatsapp_alert(message):
    if not WHATSAPP_TOKEN:
        print("WhatsApp not configured - simulating")
        return {"status": "simulated", "message": message}
    url     = f"https://graph.facebook.com/v19.0/{WHATSAPP_PHONE_ID}/messages"
    headers = {"Authorization": f"Bearer {WHATSAPP_TOKEN}", "Content-Type": "application/json"}
    payload = {"messaging_product": "whatsapp", "to": WHATSAPP_TO, "type": "text", "text": {"body": message}}
    async with httpx.AsyncClient() as client:
        r = await client.post(url, json=payload, headers=headers)
        return r.json()
